# Generated by Django 6.0.5 on 2026-06-21 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('Monitor', 'Monitor'), ('Chair', 'Chair'), ('Mobile', 'Mobile'), ('Software License', 'Software License'), ('Other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned')], default='Available', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('Monitor', 'Monitor'), ('Chair', 'Chair'), ('Mobile', 'Mobile'), ('Software License', 'Software License'), ('Other', 'Other')], max_length=30)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
